kind: pipeline
name: default

steps:
- name: test
  image: node
  commands:
  - npm install
  - npm test

#- name: publish
#  image: plugins/docker
#  settings: 
#    repo: localhost/nodejs-ex
#    registry: ''
